services:

  backend:
    container_name: backend
    command: | 
      sh -c "
        python manage.py migrate &&
        python manage.py shell -c 'from backend.services.qdrant_service import init_qdrant; init_qdrant()' || true &&
        python manage.py runserver 0.0.0.0:8000
      "
    build: 
     context: ./project
    restart: always
    volumes:
      - ./project/:/backend
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - postgresql
      - qdrant
    networks:
      - app-network

  postgresql:
    container_name: postgresql
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env 
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  qdrant:
    image: qdrant/qdrant:v1.10.0
    container_name: qdrant
    restart: always
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  pgdata:
  qdrant_storage:



networks:
  app-network:
   driver: bridge
